#!/usr/bin/env python3
"""
PreToolUse hook: mechanically enforce "no agentic footprint in commits".

CLAUDE.md states this as a standing rule, but text in a context file is only
as reliable as the model's attention to it in a long session. This makes the
rule a deterministic gate instead of a hope: any `git commit`/`git commit
--amend` Bash call whose message contains an AI-attribution trailer is
denied before it runs, with a reason fed back to the model so it can retry
without the trailer.

Registered as a PreToolUse hook on the Bash tool in .claude/settings.json.
Reads the tool call as JSON on stdin; must exit 0 (allow) or 2 (deny) per the
Claude Code hooks contract, printing the deny reason to stderr.
"""
import json
import re
import sys

FOOTPRINT_PATTERNS = [
    r"co-authored-by:\s*claude",
    r"generated with\s*\[?claude",
    r"generated by\s*claude",
    r"\bclaude\s*code\b.{0,20}(generated|wrote|authored)",
    r"🤖",
]


def is_git_commit(command: str) -> bool:
    # Matches `git commit`, `git -C x commit`, chained with && or ;, etc.
    # Deliberately broad — false positives here just mean an extra hook run,
    # false negatives mean the rule silently doesn't apply.
    return bool(re.search(r"\bgit\s+(?:-\S+\s+)*commit\b", command))


def main():
    payload = json.load(sys.stdin)
    tool_name = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {})

    if tool_name != "Bash":
        sys.exit(0)

    command = tool_input.get("command", "")
    if not is_git_commit(command):
        sys.exit(0)

    lowered = command.lower()
    for pat in FOOTPRINT_PATTERNS:
        if re.search(pat, lowered):
            sys.stderr.write(
                "BLOCKED: this commit message contains an AI-attribution "
                "trailer (Co-Authored-By: Claude, 'Generated with', or "
                "similar).\n"
                "CLAUDE.md's standing rule: commits carry no agentic "
                "footprint. Remove the trailer and re-run git commit.\n"
            )
            sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
